-- =====================================================
-- Populate Cloud Data Warehouse Dimensions
-- Schema without _id columns (simplified surrogate keys)
-- =====================================================

-- =====================================================
-- Populate dim_vendor
-- =====================================================
INSERT INTO dim_vendor (vendor_key, vendor_name, is_active)
VALUES
    (1, 'Creative Mobile Technologies', TRUE),
    (2, 'VeriFone Inc.', TRUE),
    (-1, 'Unknown', FALSE)
ON CONFLICT (vendor_key) DO NOTHING;

-- =====================================================
-- Populate dim_payment_type
-- =====================================================
INSERT INTO dim_payment_type (payment_type_key, payment_name, is_electronic)
VALUES
    (1, 'Credit card', TRUE),
    (2, 'Cash', FALSE),
    (3, 'No charge', FALSE),
    (4, 'Dispute', FALSE),
    (5, 'Unknown', FALSE),
    (6, 'Voided trip', FALSE),
    (-1, 'Unknown', FALSE)
ON CONFLICT (payment_type_key) DO NOTHING;

-- =====================================================
-- Populate dim_rate_code
-- =====================================================
INSERT INTO dim_rate_code (rate_code_key, rate_code_desc)
VALUES
    (1, 'Standard rate'),
    (2, 'JFK'),
    (3, 'Newark'),
    (4, 'Nassau or Westchester'),
    (5, 'Negotiated fare'),
    (6, 'Group ride'),
    (-1, 'Unknown')
ON CONFLICT (rate_code_key) DO NOTHING;

-- =====================================================
-- Populate dim_location (NYC Taxi Zones)
-- =====================================================
INSERT INTO workspace.default.dim_location (location_key, location_id, zone_name, borough, is_airport, is_downtown, is_tourist_area, latitude, longitude)
VALUES
(1, 1, 'Newark Airport', 'EWR', TRUE, FALSE, FALSE, NULL, NULL),
(2, 2, 'Jamaica Bay', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(3, 3, 'Allerton/Pelham Gardens', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(4, 4, 'Alphabet City', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(5, 5, 'Arden Heights', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(6, 6, 'Arrochar/Fort Wadsworth', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(7, 7, 'Astoria', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(8, 8, 'Astoria Park', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(9, 9, 'Auburndale', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(10, 10, 'Baisley Park', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(11, 11, 'Bath Beach', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(12, 12, 'Battery Park', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(13, 13, 'Battery Park City', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(14, 14, 'Bay Ridge', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(15, 15, 'Bay Terrace/Fort Totten', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(16, 16, 'Bayside', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(17, 17, 'Bedford', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(18, 18, 'Bedford Park', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(19, 19, 'Bellerose', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(20, 20, 'Belmont', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(21, 21, 'Bensonhurst East', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(22, 22, 'Bensonhurst West', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(23, 23, 'Bloomfield/Emerson Hill', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(24, 24, 'Bloomingdale', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(25, 25, 'Boerum Hill', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(26, 26, 'Borough Park', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(27, 27, 'Breezy Point/Fort Tilden/Riis Beach', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(28, 28, 'Briarwood/Jamaica Hills', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(29, 29, 'Brighton Beach', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(30, 30, 'Broad Channel', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(31, 31, 'Bronx Park', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(32, 32, 'Bronxdale', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(33, 33, 'Brooklyn Heights', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(34, 34, 'Brooklyn Navy Yard', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(35, 35, 'Brownsville', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(36, 36, 'Bushwick North', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(37, 37, 'Bushwick South', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(38, 38, 'Cambria Heights', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(39, 39, 'Canarsie', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(40, 40, 'Carroll Gardens', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(41, 41, 'Central Harlem', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(42, 42, 'Central Harlem North', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(43, 43, 'Central Park', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(44, 44, 'Charleston/Tottenville', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(45, 45, 'Chinatown', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(46, 46, 'City Island', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(47, 47, 'Claremont/Bathgate', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(48, 48, 'Clinton East', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(49, 49, 'Clinton Hill', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(50, 50, 'Clinton West', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(51, 51, 'Co-Op City', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(52, 52, 'Cobble Hill', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(53, 53, 'College Point', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(54, 54, 'Columbia Street', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(55, 55, 'Coney Island', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(56, 56, 'Corona', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(57, 57, 'Corona', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(58, 58, 'Country Club', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(59, 59, 'Crotona Park', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(60, 60, 'Crotona Park East', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(61, 61, 'Crown Heights North', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(62, 62, 'Crown Heights South', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(63, 63, 'Cypress Hills', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(64, 64, 'Douglaston', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(65, 65, 'Downtown Brooklyn/MetroTech', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(66, 66, 'DUMBO/Vinegar Hill', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(67, 67, 'Dyker Heights', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(68, 68, 'East Chelsea', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(69, 69, 'East Concourse/Concourse Village', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(70, 70, 'East Elmhurst', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(71, 71, 'East Flatbush/Farragut', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(72, 72, 'East Flatbush/Remsen Village', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(73, 73, 'East Flushing', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(74, 74, 'East Harlem North', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(75, 75, 'East Harlem South', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(76, 76, 'East New York', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(77, 77, 'East New York/Pennsylvania Avenue', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(78, 78, 'East Tremont', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(79, 79, 'East Village', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(80, 80, 'East Williamsburg', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(81, 81, 'Eastchester', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(82, 82, 'Elmhurst', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(83, 83, 'Elmhurst/Maspeth', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(84, 84, "Eltingville/Annadale/Prince's Bay", 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(85, 85, 'Erasmus', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(86, 86, 'Far Rockaway', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(87, 87, 'Financial District North', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(88, 88, 'Financial District South', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(89, 89, 'Flatbush/Ditmas Park', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(90, 90, 'Flatiron', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(91, 91, 'Flatlands', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(92, 92, 'Flushing', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(93, 93, 'Flushing Meadows-Corona Park', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(94, 94, 'Fordham South', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(95, 95, 'Forest Hills', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(96, 96, 'Forest Park/Highland Park', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(97, 97, 'Fort Greene', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(98, 98, 'Fresh Meadows', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(99, 99, 'Freshkills Park', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(100, 100, 'Garment District', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(101, 101, 'Glen Oaks', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(102, 102, 'Glendale', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(103, 103, "Governor's Island/Ellis Island/Liberty Island", 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(104, 104, "Governor's Island/Ellis Island/Liberty Island", 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(105, 105, "Governor's Island/Ellis Island/Liberty Island", 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(106, 106, 'Gowanus', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(107, 107, 'Gramercy', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(108, 108, 'Gravesend', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(109, 109, 'Great Kills', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(110, 110, 'Great Kills Park', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(111, 111, 'Green-Wood Cemetery', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(112, 112, 'Greenpoint', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(113, 113, 'Greenwich Village North', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(114, 114, 'Greenwich Village South', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(115, 115, 'Grymes Hill/Clifton', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(116, 116, 'Hamilton Heights', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(117, 117, 'Hammels/Arverne', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(118, 118, 'Heartland Village/Todt Hill', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(119, 119, 'Highbridge', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(120, 120, 'Highbridge Park', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(121, 121, 'Hillcrest/Pomonok', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(122, 122, 'Hollis', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(123, 123, 'Homecrest', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(124, 124, 'Howard Beach', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(125, 125, 'Hudson Sq', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(126, 126, 'Hunts Point', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(127, 127, 'Inwood', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(128, 128, 'Inwood Hill Park', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(129, 129, 'Jackson Heights', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(130, 130, 'Jamaica', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(131, 131, 'Jamaica Estates', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(132, 132, 'JFK Airport', 'Queens', TRUE, FALSE, FALSE, NULL, NULL),
(133, 133, 'Kensington', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(134, 134, 'Kew Gardens', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(135, 135, 'Kew Gardens Hills', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(136, 136, 'Kingsbridge Heights', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(137, 137, 'Kips Bay', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(138, 138, 'LaGuardia Airport', 'Queens', TRUE, FALSE, FALSE, NULL, NULL),
(139, 139, 'Laurelton', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(140, 140, 'Lenox Hill East', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(141, 141, 'Lenox Hill West', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(142, 142, 'Lincoln Square East', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(143, 143, 'Lincoln Square West', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(144, 144, 'Little Italy/NoLiTa', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(145, 145, 'Long Island City/Hunters Point', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(146, 146, 'Long Island City/Queens Plaza', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(147, 147, 'Longwood', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(148, 148, 'Lower East Side', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(149, 149, 'Madison', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(150, 150, 'Manhattan Beach', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(151, 151, 'Manhattan Valley', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(152, 152, 'Manhattanville', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(153, 153, 'Marble Hill', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(154, 154, 'Marine Park/Floyd Bennett Field', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(155, 155, 'Marine Park/Mill Basin', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(156, 156, 'Mariners Harbor', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(157, 157, 'Maspeth', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(158, 158, 'Meatpacking/West Village West', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(159, 159, 'Melrose South', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(160, 160, 'Middle Village', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(161, 161, 'Midtown Center', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(162, 162, 'Midtown East', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(163, 163, 'Midtown North', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(164, 164, 'Midtown South', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(165, 165, 'Midwood', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(166, 166, 'Morningside Heights', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(167, 167, 'Morrisania/Melrose', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(168, 168, 'Mott Haven/Port Morris', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(169, 169, 'Mount Hope', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(170, 170, 'Murray Hill', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(171, 171, 'Murray Hill-Queens', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(172, 172, 'New Dorp/Midland Beach', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(173, 173, 'North Corona', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(174, 174, 'Norwood', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(175, 175, 'Oakland Gardens', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(176, 176, 'Oakwood', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(177, 177, 'Ocean Hill', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(178, 178, 'Ocean Parkway South', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(179, 179, 'Old Astoria', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(180, 180, 'Ozone Park', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(181, 181, 'Park Slope', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(182, 182, 'Parkchester', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(183, 183, 'Pelham Bay', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(184, 184, 'Pelham Bay Park', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(185, 185, 'Pelham Parkway', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(186, 186, 'Penn Station/Madison Sq West', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(187, 187, 'Port Richmond', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(188, 188, 'Prospect-Lefferts Gardens', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(189, 189, 'Prospect Heights', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(190, 190, 'Prospect Park', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(191, 191, 'Queens Village', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(192, 192, 'Queensboro Hill', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(193, 193, 'Queensbridge/Ravenswood', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(194, 194, 'Randalls Island', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(195, 195, 'Red Hook', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(196, 196, 'Rego Park', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(197, 197, 'Richmond Hill', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(198, 198, 'Ridgewood', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(199, 199, 'Rikers Island', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(200, 200, 'Riverdale/North Riverdale/Fieldston', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(201, 201, 'Rockaway Park', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(202, 202, 'Roosevelt Island', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(203, 203, 'Rosedale', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(204, 204, 'Rossville/Woodrow', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(205, 205, 'Saint Albans', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(206, 206, 'Saint George/New Brighton', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(207, 207, 'Saint Michaels Cemetery/Woodside', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(208, 208, 'Schuylerville/Edgewater Park', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(209, 209, 'Seaport', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(210, 210, 'Sheepshead Bay', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(211, 211, 'SoHo', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(212, 212, 'Soundview/Bruckner', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(213, 213, 'Soundview/Castle Hill', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(214, 214, 'South Beach/Dongan Hills', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(215, 215, 'South Jamaica', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(216, 216, 'South Ozone Park', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(217, 217, 'South Williamsburg', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(218, 218, 'Springfield Gardens North', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(219, 219, 'Springfield Gardens South', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(220, 220, 'Spuyten Duyvil/Kingsbridge', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(221, 221, 'Stapleton', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(222, 222, 'Starrett City', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(223, 223, 'Steinway', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(224, 224, 'Stuy Town/Peter Cooper Village', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(225, 225, 'Stuyvesant Heights', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(226, 226, 'Sunnyside', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(227, 227, 'Sunset Park East', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(228, 228, 'Sunset Park West', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(229, 229, 'Sutton Place/Turtle Bay North', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(230, 230, 'Times Sq/Theatre District', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(231, 231, 'TriBeCa/Civic Center', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(232, 232, 'Two Bridges/Seward Park', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(233, 233, 'UN/Turtle Bay South', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(234, 234, 'Union Sq', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(235, 235, 'University Heights/Morris Heights', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(236, 236, 'Upper East Side North', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(237, 237, 'Upper East Side South', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(238, 238, 'Upper West Side North', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(239, 239, 'Upper West Side South', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(240, 240, 'Van Cortlandt Park', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(241, 241, 'Van Cortlandt Village', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(242, 242, 'Van Nest/Morris Park', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(243, 243, 'Washington Heights North', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(244, 244, 'Washington Heights South', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(245, 245, 'West Brighton', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(246, 246, 'West Chelsea/Hudson Yards', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(247, 247, 'West Concourse', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(248, 248, 'West Farms/Bronx River', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(249, 249, 'West Village', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(250, 250, 'Westchester Village/Unionport', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(251, 251, 'Westerleigh', 'Staten Island', FALSE, FALSE, FALSE, NULL, NULL),
(252, 252, 'Whitestone', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(253, 253, 'Willets Point', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(254, 254, 'Williamsbridge/Olinville', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(255, 255, 'Williamsburg (North Side)', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(256, 256, 'Williamsburg (South Side)', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(257, 257, 'Windsor Terrace', 'Brooklyn', FALSE, FALSE, FALSE, NULL, NULL),
(258, 258, 'Woodhaven', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(259, 259, 'Woodlawn/Wakefield', 'Bronx', FALSE, FALSE, FALSE, NULL, NULL),
(260, 260, 'Woodside', 'Queens', FALSE, FALSE, FALSE, NULL, NULL),
(261, 261, 'World Trade Center', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(262, 262, 'Yorkville East', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(263, 263, 'Yorkville West', 'Manhattan', FALSE, FALSE, FALSE, NULL, NULL),
(264, 264, 'N/A', 'Unknown', FALSE, FALSE, FALSE, NULL, NULL),
(265, 265, 'Outside of NYC', 'N/A', FALSE, FALSE, FALSE, NULL, NULL);
ON CONFLICT (location_key) DO NOTHING;


-- correct the counties name with the currect version of databricks
update  dim_location set borough = 'Bronx' where borough = 'Bronx';
update  dim_location set borough = 'Kings' where borough = 'Brooklyn';
update  dim_location set borough = 'New York' where borough = 'Manhattan';
update  dim_location set borough = 'Richmond' where borough = 'Staten Island';
update  dim_location set borough = 'Essex' where borough = 'EWR';


-- Add more locations as needed (265 total zones available)
